'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AltaEgreso

    '''<summary>
    '''CLHGHT008 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT008 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FormAltaEgreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormAltaEgreso As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ddlProrrateo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProrrateo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlUnidadesFuncionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidadesFuncionales As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CLHXXXXX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHXXXXX As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
