'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientesHome

    '''<summary>
    '''FormClientesHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormClientesHome As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CLHGHT001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT001 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CLHGHT002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT002 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CLHGHT003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT003 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CLHGHT004 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT004 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CLHGHT005 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT005 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
