'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Consorcios

    '''<summary>
    '''FormClientesConsorcios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormClientesConsorcios As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CLHGHT008 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT008 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ConsultaConsorciosGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConsultaConsorciosGridView As Global.System.Web.UI.WebControls.GridView
End Class
