'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Expensas

    '''<summary>
    '''FormExpensas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormExpensas As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CLHGHT005 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT005 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlExpensas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExpensas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ConsultaExpensasGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConsultaExpensasGridView As Global.System.Web.UI.WebControls.GridView
End Class
