'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UnidadesFuncionales

    '''<summary>
    '''FormUnidadesFuncionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormUnidadesFuncionales As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CLHGHT013 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLHGHT013 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlConsorcios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConsorcios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ConsultaUnidadesFuncionalesGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConsultaUnidadesFuncionalesGridView As Global.System.Web.UI.WebControls.GridView
End Class
